### PR TITLE
process_swept_Langmuir self test

### PR DESCRIPTION
**Pull request by lurudisch**
The self test of the above function was not working probably due to some p2.7 function calls, now it runs provided a shot_DA has been created.

### CODE REVIEW

**Comment by bdb112** [comment]
THanks lukas.  Will look at this tomorrow.

ps: see what has been distracting me

https://www.flickr.com/photos/boyd_blackwell/29322276074/in/datetaken-ff/


________________________________

**Review by bdb112 — COMMENTED** [review]
Hi Lukas - didn't see the Codac examples - can you give A url to that example

Does the loads().

**Review by bdb112 — COMMENTED** [review]
Sorry about the mucked up comment
I will try again.

Thanks for your suggestions. 

1/ load vs. loads 
I didn't know about that CoDaC example - happy to conform to the example.  Can you provide a url link to that example, so we can include it in a comment?

Have you tested the loads version in 2.7?  If not I can do it in a day or two - I have to log on to the Windows server.

2/ The loads() in get shot list might need read().deocde() also?

3/ In process-swept_Langmuir, the changes line 695 looks a little strange - what was your intention?

**Comment by lurudisch** [comment]
1/ The example I'm referring to is here: http://webservices.ipp-hgw.mpg.de/docs/howtoREST.html#python, this is what I've been using in the code I wrote previously as well. The 'utf-8' option in decode isn't necessary as it's the default anyway.
I have not tested in python version 2.7, however looking at the documentation of json at https://docs.python.org/**[2 OR 3]**/library/json.html#basic-usage respectively it seems the difference between load and loads is in the type of objects that can be decoded. These are fp .read() supporting objects in both p versions for load() and str or unicode instances for loads() in p2.7, but only the former in p3.
2/ It wasn't necessary to change anything, perhaps the object type passed to loads() in get_shot_list is compatible without the read() or it is done by default?
3/ The problem was the np.mean(mseg.timebase) was returning a timebase object (I don't quite understand why not simply a number) and round() calls the magic/basic __round__() method of that object, which it doesn't posess. My fix simply removed the round, which left the 4 digits option stranded. A better fix is to use np.round which I have done, I will upload the change shortly.

**Pull request closed without merging**
